let carros = [
  {
    id: 1,
    nome: "Relâmpago McQueen",
    modelo: "Carro de corrida",
    ano: 2006,
    cor: "Vermelho",
    qtdeVitorias: 8,
  },
  {
    id: 2,
    nome: "Doc Hudson",
    modelo: "Carro de corrida",
    ano: 1951,
    cor: "Azul",
    qtdeVitorias: 5,
  },
  {
    id: 3,
    nome: "Mate",
    modelo: "Reboque",
    ano: 1955,
    cor: "Marrom",
    qtdeVitorias: 0,
  },
  {
    id: 4,
    nome: "Francesco Bernoulli",
    modelo: "Carro de corrida",
    ano: 2012,
    cor: "Verde",
    qtdeVitorias: 6,
  },
  {
    id: 5,
    nome: "Sally Carrera",
    modelo: "Porsche",
    ano: 2002,
    cor: "Azul",
    qtdeVitorias: 0,
  },
  {
    id: 6,
    nome: "Ramone",
    modelo: "Customizado",
    ano: 1959,
    cor: "Roxo",
    qtdeVitorias: 0,
  },
  {
    id: 7,
    nome: "Guido",
    modelo: "Empilhadeira",
    ano: 1999,
    cor: "Azul",
    qtdeVitorias: 0,
  },
  {
    id: 8,
    nome: "Shu Todoroki",
    modelo: "Carro de corrida",
    ano: 2010,
    cor: "Branco com detalhes vermelhos",
    qtdeVitorias: 2,
  },
  {
    id: 9,
    nome: "Carlos Veloso",
    modelo: "Carro de corrida",
    ano: 2012,
    cor: "Amarelo",
    qtdeVitorias: 3,
  },
  {
    id: 10,
    nome: "Miguel Camino",
    modelo: "Carro de corrida",
    ano: 2010,
    cor: "Laranja com detalhes amarelos",
    qtdeVitorias: 1,
  },
  {
    id: 11,
    nome: "Chick Hicks",
    modelo: "Carro de corrida",
    ano: 2006,
    cor: "Verde",
    qtdeVitorias: 4,
  },
  {
    id: 12,
    nome: "Holley Shiftwell",
    modelo: "Carro espião",
    ano: 2011,
    cor: "Azul metálico",
    qtdeVitorias: 0,
  },
  {
    id: 13,
    nome: "Francesco Bernoulli",
    modelo: "Carro de corrida",
    ano: 2012,
    cor: "Verde com detalhes vermelhos",
    qtdeVitorias: 6,
  },
  {
    id: 14,
    nome: "Max Schnell",
    modelo: "Carro de corrida",
    ano: 2010,
    cor: "Azul com detalhes prateados",
    qtdeVitorias: 0,
  }
];

export default {carros};
